import { Geist, Geist_Mono, Jost } from "next/font/google";
import "./globals.css";
import Headers from "@/components/Headers/Headers";
import ClientWrapper from "@/components/ClientWrapper/ClientWrapper";
import Footer3 from "@/components/Shadcn/Footer3/Footer3";
import ConditionalLayout from "@/components/ConditionalLayout/ConditionalLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const jost = Jost({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sellkar Theme 2",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        className={`${jost.className} antialiased`}
        suppressHydrationWarning
      >
        <ClientWrapper>
          <ConditionalLayout>
            {children}
          </ConditionalLayout>
        </ClientWrapper>
      </body>
    </html>
  );
}